// <auto-generated />
using System;
using AzureOverview.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzureOverview.Data.Migrations
{
    [DbContext(typeof(AzureOverviewContext))]
    partial class AzureOverviewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzureOverview.Data.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("GeneralAvailabilityDate");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("PublicPreviewDate");

                    b.Property<string>("Status");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new { Id = new Guid("1bf83047-ecb0-4c01-8729-054d58c7d6cb"), Category = "COMPUTE", Description = "Azure Batch makes it easy to run large-scale parallel and high-performance computing (HPC) workloads in Azure. Use Batch to scale out parallel workloads, manage the execution of tasks in a queue, and cloud-enable applications to offload compute jobs to the cloud.", GeneralAvailabilityDate = new DateTime(2015, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), ImageUrl = "Azure Batch.png", Name = "Azure Batch", PublicPreviewDate = new DateTime(2014, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), Status = "Generally Available", Url = "https://azure.microsoft.com/services/batch/" },
                        new { Id = new Guid("4a85d590-ac85-4306-b73c-87882172a5b8"), Category = "WEB & MOBILE", Description = "The Web Apps feature in Azure App Service lets developers rapidly build, deploy, and manage powerful websites and web apps. Build standards-based web apps and APIs using .NET, Node.js, PHP, Python, and Java. Deliver both web and mobile apps for employees or customers using a single back end. Securely deliver APIs that enable additional apps and devices.", GeneralAvailabilityDate = new DateTime(2015, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), ImageUrl = "Web App (was Websites).png", Name = "App Service Web App", Status = "Generally Available", Url = "https://azure.microsoft.com/nl-nl/services/app-service/web/" },
                        new { Id = new Guid("f1b57d1b-c0a8-4ced-bf11-89acc5103d68"), Category = "COMPUTE", Description = "Service Fabric is a microservices platform used to build scalable, reliable, and easily managed applications for the cloud. Addressing the significant challenges in developing and managing cloud applications, Service Fabric allows developers and administrators to avoid solving complex infrastructure problems and focus instead on implementing mission-critical, demanding workloads.", GeneralAvailabilityDate = new DateTime(2016, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), ImageUrl = "Service Fabric.png", Name = "Service Fabric", PublicPreviewDate = new DateTime(2015, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), Status = "Generally Available", Url = "https://azure.microsoft.com/services/service-fabric/" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
